# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: club_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Protos import pagination_pb2 as Protos_dot_pagination__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63lub_service.proto\x12\x0c\x63lub_service\x1a\x17Protos/pagination.proto\"t\n\x0e\x41\x64\x64\x43lubRequest\x12\x11\n\troom_code\x18\x01 \x01(\t\x12\x11\n\troom_name\x18\x02 \x01(\t\x12\x11\n\x04guid\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07room_id\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_guidB\n\n\x08_room_id\"Q\n\x0eGetClubRequest\x12\x0e\n\x04guid\x18\x01 \x01(\tH\x00\x12\x13\n\troom_code\x18\x02 \x01(\tH\x00\x12\x11\n\x07room_id\x18\x03 \x01(\tH\x00\x42\x07\n\x05query\"\x7f\n\x13GetAllClubsResponse\x12)\n\x05\x63lubs\x18\x01 \x03(\x0b\x32\x1a.club_service.ClubResponse\x12=\n\npagination\x18\x02 \x01(\x0b\x32).PaginationGrpc.PaginationResponseMessage\"d\n\x0c\x43lubResponse\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x11\n\troom_code\x18\x02 \x01(\t\x12\x11\n\troom_name\x18\x03 \x01(\t\x12\x14\n\x07room_id\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_room_id\"H\n\x11\x43lubFilterMessage\x12\r\n\x05guids\x18\x01 \x03(\t\x12\x12\n\nroom_codes\x18\x02 \x03(\t\x12\x10\n\x08room_ids\x18\x03 \x03(\t\"\x93\x01\n\x12GetAllClubsRequest\x12<\n\npagination\x18\x01 \x01(\x0b\x32(.PaginationGrpc.PaginationRequestMessage\x12\x34\n\x06\x66ilter\x18\x02 \x01(\x0b\x32\x1f.club_service.ClubFilterMessageH\x00\x88\x01\x01\x42\t\n\x07_filter2\xf7\x01\n\x0f\x43lubServiceGrpc\x12K\n\x0f\x41\x64\x64OrUpdateClub\x12\x1c.club_service.AddClubRequest\x1a\x1a.club_service.ClubResponse\x12\x43\n\x07GetClub\x12\x1c.club_service.GetClubRequest\x1a\x1a.club_service.ClubResponse\x12R\n\x0bGetAllClubs\x12 .club_service.GetAllClubsRequest\x1a!.club_service.GetAllClubsResponseB\x12\xaa\x02\x0f\x43lubServiceGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'club_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017ClubServiceGrpc'
  _globals['_ADDCLUBREQUEST']._serialized_start=61
  _globals['_ADDCLUBREQUEST']._serialized_end=177
  _globals['_GETCLUBREQUEST']._serialized_start=179
  _globals['_GETCLUBREQUEST']._serialized_end=260
  _globals['_GETALLCLUBSRESPONSE']._serialized_start=262
  _globals['_GETALLCLUBSRESPONSE']._serialized_end=389
  _globals['_CLUBRESPONSE']._serialized_start=391
  _globals['_CLUBRESPONSE']._serialized_end=491
  _globals['_CLUBFILTERMESSAGE']._serialized_start=493
  _globals['_CLUBFILTERMESSAGE']._serialized_end=565
  _globals['_GETALLCLUBSREQUEST']._serialized_start=568
  _globals['_GETALLCLUBSREQUEST']._serialized_end=715
  _globals['_CLUBSERVICEGRPC']._serialized_start=718
  _globals['_CLUBSERVICEGRPC']._serialized_end=965
# @@protoc_insertion_point(module_scope)
