# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import club_service_pb2 as club__service__pb2

GRPC_GENERATED_VERSION = '1.65.2'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in club_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ClubServiceGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddOrUpdateClub = channel.unary_unary(
                '/club_service.ClubServiceGrpc/AddOrUpdateClub',
                request_serializer=club__service__pb2.AddClubRequest.SerializeToString,
                response_deserializer=club__service__pb2.ClubResponse.FromString,
                _registered_method=True)
        self.GetClub = channel.unary_unary(
                '/club_service.ClubServiceGrpc/GetClub',
                request_serializer=club__service__pb2.GetClubRequest.SerializeToString,
                response_deserializer=club__service__pb2.ClubResponse.FromString,
                _registered_method=True)
        self.GetAllClubs = channel.unary_unary(
                '/club_service.ClubServiceGrpc/GetAllClubs',
                request_serializer=club__service__pb2.GetAllClubsRequest.SerializeToString,
                response_deserializer=club__service__pb2.GetAllClubsResponse.FromString,
                _registered_method=True)


class ClubServiceGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddOrUpdateClub(self, request, context):
        """
        if club with guid, room_code or room_id was created updates club name
        else creates club with provided identifiers.

        if provided guid and no club with room_code or room_id created generated new guid.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllClubs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClubServiceGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddOrUpdateClub': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOrUpdateClub,
                    request_deserializer=club__service__pb2.AddClubRequest.FromString,
                    response_serializer=club__service__pb2.ClubResponse.SerializeToString,
            ),
            'GetClub': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClub,
                    request_deserializer=club__service__pb2.GetClubRequest.FromString,
                    response_serializer=club__service__pb2.ClubResponse.SerializeToString,
            ),
            'GetAllClubs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllClubs,
                    request_deserializer=club__service__pb2.GetAllClubsRequest.FromString,
                    response_serializer=club__service__pb2.GetAllClubsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'club_service.ClubServiceGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('club_service.ClubServiceGrpc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClubServiceGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddOrUpdateClub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/club_service.ClubServiceGrpc/AddOrUpdateClub',
            club__service__pb2.AddClubRequest.SerializeToString,
            club__service__pb2.ClubResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/club_service.ClubServiceGrpc/GetClub',
            club__service__pb2.GetClubRequest.SerializeToString,
            club__service__pb2.ClubResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllClubs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/club_service.ClubServiceGrpc/GetAllClubs',
            club__service__pb2.GetAllClubsRequest.SerializeToString,
            club__service__pb2.GetAllClubsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
