# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/pagination.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17Protos/pagination.proto\x12\x0ePaginationGrpc\x1a\x1egoogle/protobuf/wrappers.proto\"@\n\x18PaginationRequestMessage\x12\x16\n\x0eper_page_count\x18\x01 \x01(\x05\x12\x0c\n\x04page\x18\x02 \x01(\x05\"\x94\x01\n\x19PaginationResponseMessage\x12.\n\tnext_page\x18\x01 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x32\n\rprevious_page\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x13\n\x0btotal_pages\x18\x03 \x01(\x05\x42\x11\xaa\x02\x0ePaginationGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protos.pagination_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016PaginationGrpc'
  _globals['_PAGINATIONREQUESTMESSAGE']._serialized_start=75
  _globals['_PAGINATIONREQUESTMESSAGE']._serialized_end=139
  _globals['_PAGINATIONRESPONSEMESSAGE']._serialized_start=142
  _globals['_PAGINATIONRESPONSEMESSAGE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
